name: "my_new_project"
version: "1.0.0"
config-version: 2

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
models:
  materialized: 'table'
